spring.application.name=TTARAGA
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html

spring.datasource.url=jdbc:mariadb://db-ttaraga.c7e4424yswrm.ap-northeast-2.rds.amazonaws.com:3306/ttaraga_db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=ttaraga!
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


seoul.api.key=7747754d61736d303935746e444267
seoul.api.bike = 4e704f70546a696838314b526e4e6a

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
